In [11]:
import pandas as pd
import datetime as dt

In [2]:
feb_df=pd.read_csv("data/feb2020.csv")
feb_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1404,2020-02-01 00:00:05.9460,2020-02-01 00:23:30.7240,316,Fulton St & William St,40.709560,-74.006536,481,S 3 St & Bedford Ave,40.712605,-73.962644,28874,Customer,1995,1
1,1301,2020-02-01 00:00:06.2230,2020-02-01 00:21:48.0580,237,E 11 St & 2 Ave,40.730473,-73.986724,539,Metropolitan Ave & Bedford Ave,40.715348,-73.960241,32588,Subscriber,1991,1
2,474,2020-02-01 00:00:15.7210,2020-02-01 00:08:10.3440,528,2 Ave & E 31 St,40.742909,-73.977061,3785,W 42 St & 6 Ave,40.754920,-73.984550,41013,Subscriber,1994,1
3,487,2020-02-01 00:00:21.0520,2020-02-01 00:08:28.7520,380,W 4 St & 7 Ave S,40.734011,-74.002939,3263,Cooper Square & Astor Pl,40.729515,-73.990753,27581,Subscriber,1973,2
4,619,2020-02-01 00:00:27.4000,2020-02-01 00:10:47.0640,472,E 32 St & Park Ave,40.745712,-73.981948,237,E 11 St & 2 Ave,40.730473,-73.986724,29062,Subscriber,1994,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1146825,203,2020-02-29 23:58:48.0230,2020-03-01 00:02:11.6640,3737,Stanton St & Norfolk St,40.720747,-73.986274,317,E 6 St & Avenue B,40.724537,-73.981854,39094,Subscriber,1993,2
1146826,357,2020-02-29 23:58:52.5640,2020-03-01 00:04:50.5370,546,E 30 St & Park Ave S,40.744449,-73.983035,3463,E 16 St & Irving Pl,40.735367,-73.987974,40722,Subscriber,1966,2
1146827,169,2020-02-29 23:58:54.5820,2020-03-01 00:01:43.7770,3043,Lewis Ave & Decatur St,40.681460,-73.934903,3052,Lewis Ave & Madison St,40.686312,-73.935775,28696,Subscriber,1994,1
1146828,738,2020-02-29 23:58:58.8110,2020-03-01 00:11:17.7390,3255,8 Ave & W 31 St,40.750585,-73.994685,497,E 17 St & Broadway,40.737050,-73.990093,19975,Subscriber,1999,1
1146829,960,2020-02-29 23:59:35.6070,2020-03-01 00:15:35.6490,379,W 31 St & 7 Ave,40.749156,-73.991600,3744,1 Ave & E 5 St,40.725864,-73.986389,38651,Subscriber,1990,1

In [3]:
feb_df["starttime"]=feb_df["starttime"].astype(str).str[:-5]
feb_df["stoptime"]=feb_df["stoptime"].astype(str).str[:-5]
feb_df['startdate'], feb_df['starttime'] = feb_df['starttime'].str.split(' ', 1).str
feb_df['stopdate'], feb_df['stoptime'] = feb_df['stoptime'].str.split(' ', 1).str
feb_df["startdate"]=pd.to_datetime(feb_df["startdate"], format='%Y-%m-%d')
feb_df=feb_df.loc[feb_df["startdate"]> "2020-2-20"]
feb_df

C:\Users\paras\Anaconda3\envs\PythonData2020_1\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\paras\Anaconda3\envs\PythonData2020_1\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  after removing the cwd from sys.path.

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,startdate,stopdate
765010,253,00:00:05,00:04:19,3526,31 St & 23 Ave,40.774788,-73.912555,3532,Ditmars Blvd & 19 St,40.781450,-73.918330,32770,Subscriber,1990,1,2020-02-21,2020-02-21
765011,337,00:00:10,00:05:48,460,S 4 St & Wythe Ave,40.712859,-73.965903,3093,N 6 St & Bedford Ave,40.717452,-73.958509,40350,Subscriber,1982,1,2020-02-21,2020-02-21
765012,258,00:00:24,00:04:42,387,Centre St & Chambers St,40.712733,-74.004607,82,St James Pl & Pearl St,40.711174,-74.000165,30474,Subscriber,1987,1,2020-02-21,2020-02-21
765013,1961,00:00:25,00:33:06,3146,E 81 St & 3 Ave,40.775730,-73.956753,445,E 10 St & Avenue A,40.727408,-73.981420,14654,Subscriber,1976,2,2020-02-21,2020-02-21
765014,690,00:00:25,00:11:56,3410,Dean St & Hoyt St,40.686444,-73.987591,3574,Prospect Pl & Underhill Ave,40.676969,-73.965790,39451,Subscriber,1980,1,2020-02-21,2020-02-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1146825,203,23:58:48,00:02:11,3737,Stanton St & Norfolk St,40.720747,-73.986274,317,E 6 St & Avenue B,40.724537,-73.981854,39094,Subscriber,1993,2,2020-02-29,2020-03-01
1146826,357,23:58:52,00:04:50,546,E 30 St & Park Ave S,40.744449,-73.983035,3463,E 16 St & Irving Pl,40.735367,-73.987974,40722,Subscriber,1966,2,2020-02-29,2020-03-01
1146827,169,23:58:54,00:01:43,3043,Lewis Ave & Decatur St,40.681460,-73.934903,3052,Lewis Ave & Madison St,40.686312,-73.935775,28696,Subscriber,1994,1,2020-02-29,2020-03-01
1146828,738,23:58:58,00:11:17,3255,8 Ave & W 31 St,40.750585,-73.994685,497,E 17 St & Broadway,40.737050,-73.990093,19975,Subscriber,1999,1,2020-02-29,2020-03-01
1146829,960,23:59:35,00:15:35,379,W 31 St & 7 Ave,40.749156,-73.991600,3744,1 Ave & E 5 St,40.725864,-73.986389,38651,Subscriber,1990,1,2020-02-29,2020-03-01

In [ ]:
feb_df.to_csv("db/feb.csv")

In [4]:
apr_df=pd.read_csv("data/apr2020.csv")
apr_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,534,2020-04-01 00:00:15.2800,2020-04-01 00:09:09.8730,3656,E 2 St & Avenue A,40.723077,-73.985836,545,E 23 St & 1 Ave,40.736502,-73.978095,15162,Subscriber,1990,2
1,529,2020-04-01 00:02:28.9430,2020-04-01 00:11:18.3410,3163,Central Park West & W 68 St,40.773407,-73.977825,3301,Columbus Ave & W 95 St,40.791956,-73.968087,42861,Subscriber,1974,1
2,1488,2020-04-01 00:02:56.0900,2020-04-01 00:27:44.2530,3164,Columbus Ave & W 72 St,40.777057,-73.978985,3605,31 Ave & Crescent St,40.765835,-73.926547,35989,Subscriber,1982,1
3,341,2020-04-01 00:03:25.1410,2020-04-01 00:09:06.3190,3827,Halsey St & Broadway,40.685650,-73.915640,3869,Van Buren St & Broadway,40.692000,-73.926170,37548,Subscriber,1996,1
4,2206,2020-04-01 00:05:35.2790,2020-04-01 00:42:21.9080,3890,Grove St & Broadway,40.690470,-73.923511,3058,Lewis Ave & Kosciuszko St,40.692371,-73.937054,39701,Subscriber,1977,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
682757,1680,2020-04-30 23:59:00.7780,2020-05-01 00:27:01.7600,447,8 Ave & W 52 St,40.763707,-73.985162,2021,W 45 St & 8 Ave,40.759291,-73.988597,43888,Subscriber,1989,1
682758,1334,2020-04-30 23:59:23.6460,2020-05-01 00:21:38.2190,3292,5 Ave & E 93 St,40.785785,-73.957481,509,9 Ave & W 22 St,40.745497,-74.001971,36853,Subscriber,1973,1
682759,1334,2020-04-30 23:59:33.6760,2020-05-01 00:21:48.2150,3292,5 Ave & E 93 St,40.785785,-73.957481,509,9 Ave & W 22 St,40.745497,-74.001971,37808,Subscriber,1981,1
682760,234,2020-04-30 23:59:56.9720,2020-05-01 00:03:51.9600,469,Broadway & W 53 St,40.763441,-73.982681,495,W 47 St & 10 Ave,40.762699,-73.993012,20635,Subscriber,1996,2
682761,267,2020-04-30 23:59:59.3510,2020-05-01 00:04:26.8110,3812,University Pl & E 14 St,40.734814,-73.992085,503,E 20 St & Park Ave,40.738274,-73.987520,37530,Subscriber,1980,1

In [5]:
apr_df["starttime"]=apr_df["starttime"].astype(str).str[:-5]
apr_df["stoptime"]=apr_df["stoptime"].astype(str).str[:-5]
apr_df['startdate'], apr_df['starttime'] = apr_df['starttime'].str.split(' ', 1).str
apr_df['stopdate'], apr_df['stoptime'] = apr_df['stoptime'].str.split(' ', 1).str
apr_df["startdate"]=pd.to_datetime(apr_df["startdate"], format='%Y-%m-%d')
apr_df=apr_df.loc[apr_df["startdate"]> "2020-4-20"]
apr_df

C:\Users\paras\Anaconda3\envs\PythonData2020_1\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\paras\Anaconda3\envs\PythonData2020_1\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  after removing the cwd from sys.path.

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,startdate,stopdate
448101,777,00:00:21,00:13:18,3150,E 85 St & York Ave,40.775369,-73.948034,3150,E 85 St & York Ave,40.775369,-73.948034,43156,Subscriber,1981,1,2020-04-21,2020-04-21
448102,348,00:01:05,00:06:53,501,FDR Drive & E 35 St,40.744219,-73.971212,3733,Avenue C & E 18 St,40.730563,-73.973984,38629,Subscriber,2001,1,2020-04-21,2020-04-21
448103,286,00:01:17,00:06:03,3783,Cliff St & Fulton St,40.708380,-74.004950,417,Barclay St & Church St,40.712912,-74.010202,18420,Subscriber,1966,1,2020-04-21,2020-04-21
448104,1106,00:01:21,00:19:48,3641,Broadway & W 25 St,40.742869,-73.989186,497,E 17 St & Broadway,40.737050,-73.990093,37619,Customer,1990,0,2020-04-21,2020-04-21
448105,462,00:01:40,00:09:23,486,Broadway & W 29 St,40.746201,-73.988557,496,E 16 St & 5 Ave,40.737262,-73.992390,39424,Subscriber,1961,2,2020-04-21,2020-04-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
682757,1680,23:59:00,00:27:01,447,8 Ave & W 52 St,40.763707,-73.985162,2021,W 45 St & 8 Ave,40.759291,-73.988597,43888,Subscriber,1989,1,2020-04-30,2020-05-01
682758,1334,23:59:23,00:21:38,3292,5 Ave & E 93 St,40.785785,-73.957481,509,9 Ave & W 22 St,40.745497,-74.001971,36853,Subscriber,1973,1,2020-04-30,2020-05-01
682759,1334,23:59:33,00:21:48,3292,5 Ave & E 93 St,40.785785,-73.957481,509,9 Ave & W 22 St,40.745497,-74.001971,37808,Subscriber,1981,1,2020-04-30,2020-05-01
682760,234,23:59:56,00:03:51,469,Broadway & W 53 St,40.763441,-73.982681,495,W 47 St & 10 Ave,40.762699,-73.993012,20635,Subscriber,1996,2,2020-04-30,2020-05-01
682761,267,23:59:59,00:04:26,3812,University Pl & E 14 St,40.734814,-73.992085,503,E 20 St & Park Ave,40.738274,-73.987520,37530,Subscriber,1980,1,2020-04-30,2020-05-01

In [ ]:
apr_df.to_csv("db/apr.csv")

In [13]:
june_df=pd.read_csv("data/june2020.csv")
june_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1062,2020-06-01 00:00:03.3720,2020-06-01 00:17:46.2080,3419,Douglass St & 4 Ave,40.679279,-73.981540,3419,Douglass St & 4 Ave,40.679279,-73.981540,39852,Customer,1997,2
1,3810,2020-06-01 00:00:03.5530,2020-06-01 01:03:33.9360,366,Clinton Ave & Myrtle Ave,40.693261,-73.968896,336,Sullivan St & Washington Sq,40.730477,-73.999061,37558,Subscriber,1969,0
2,1017,2020-06-01 00:00:09.6140,2020-06-01 00:17:06.8330,389,Broadway & Berry St,40.710446,-73.965251,3562,Classon Ave & St Marks Ave,40.676520,-73.959608,37512,Customer,1988,2
3,226,2020-06-01 00:00:12.1780,2020-06-01 00:03:58.8640,3255,8 Ave & W 31 St,40.750585,-73.994685,505,6 Ave & W 33 St,40.749013,-73.988484,39674,Customer,1969,0
4,1437,2020-06-01 00:00:21.2550,2020-06-01 00:24:18.9650,367,E 53 St & Lexington Ave,40.758281,-73.970694,497,E 17 St & Broadway,40.737050,-73.990093,21093,Customer,1997,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1882268,685,2020-06-30 23:59:41.1160,2020-07-01 00:11:06.7790,503,E 20 St & Park Ave,40.738274,-73.987520,3746,6 Ave & Broome St,40.724308,-74.004730,21056,Customer,1993,2
1882269,446,2020-06-30 23:59:46.4260,2020-07-01 00:07:13.0860,3699,W 50 St & 9 Ave,40.763605,-73.989180,523,W 38 St & 8 Ave,40.754666,-73.991382,30164,Customer,1969,0
1882270,439,2020-06-30 23:59:47.4770,2020-07-01 00:07:06.5590,3699,W 50 St & 9 Ave,40.763605,-73.989180,523,W 38 St & 8 Ave,40.754666,-73.991382,43742,Customer,1986,1
1882271,890,2020-06-30 23:59:53.3950,2020-07-01 00:14:43.4270,3852,Stewart Ave & Johnson Ave,40.708690,-73.925870,3054,Greene Ave & Throop Ave,40.689493,-73.942061,15787,Subscriber,1994,1
1882272,433,2020-06-30 23:59:53.9010,2020-07-01 00:07:07.0950,324,DeKalb Ave & Hudson Ave,40.689888,-73.981013,261,Johnson St & Gold St,40.694749,-73.983625,38767,Customer,1990,1

In [15]:
june_df["starttime"]=june_df["starttime"].astype(str).str[:-5]
june_df["stoptime"]=june_df["stoptime"].astype(str).str[:-5]
june_df['startdate'], june_df['starttime'] = june_df['starttime'].str.split(' ', 1).str
june_df['stopdate'], june_df['stoptime'] = june_df['stoptime'].str.split(' ', 1).str
june_df["startdate"]=pd.to_datetime(june_df["startdate"], format='%Y-%m-%d')
june_df=june_df.loc[june_df["startdate"]> "2020-6-20"]
june_df

C:\Users\paras\Anaconda3\envs\PythonData2020_1\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\paras\Anaconda3\envs\PythonData2020_1\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  after removing the cwd from sys.path.

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,startdate,stopdate
1217979,819,00:00:00,00:13:40,312,Allen St & Stanton St,40.722055,-73.989111,481,S 3 St & Bedford Ave,40.712605,-73.962644,38733,Subscriber,1997,2,2020-06-21,2020-06-21
1217980,961,00:00:04,00:16:05,3708,W 13 St & 5 Ave,40.735445,-73.994310,3435,Grand St & Elizabeth St,40.718822,-73.995960,38183,Customer,1998,2,2020-06-21,2020-06-21
1217981,1980,00:00:16,00:33:16,3425,2 Ave & E 104 St,40.789210,-73.943708,3603,31 Ave & 30 St,40.764700,-73.924031,31593,Subscriber,1989,1,2020-06-21,2020-06-21
1217982,1457,00:00:18,00:24:36,3995,5 Ave & E 135 St,40.812191,-73.937838,3963,Melrose Ave & E 150 St,40.816827,-73.917338,43645,Customer,1969,0,2020-06-21,2020-06-21
1217983,822,00:00:24,00:14:06,120,Lexington Ave & Classon Ave,40.686768,-73.959282,481,S 3 St & Bedford Ave,40.712605,-73.962644,41816,Customer,1969,0,2020-06-21,2020-06-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1882268,685,23:59:41,00:11:06,503,E 20 St & Park Ave,40.738274,-73.987520,3746,6 Ave & Broome St,40.724308,-74.004730,21056,Customer,1993,2,2020-06-30,2020-07-01
1882269,446,23:59:46,00:07:13,3699,W 50 St & 9 Ave,40.763605,-73.989180,523,W 38 St & 8 Ave,40.754666,-73.991382,30164,Customer,1969,0,2020-06-30,2020-07-01
1882270,439,23:59:47,00:07:06,3699,W 50 St & 9 Ave,40.763605,-73.989180,523,W 38 St & 8 Ave,40.754666,-73.991382,43742,Customer,1986,1,2020-06-30,2020-07-01
1882271,890,23:59:53,00:14:43,3852,Stewart Ave & Johnson Ave,40.708690,-73.925870,3054,Greene Ave & Throop Ave,40.689493,-73.942061,15787,Subscriber,1994,1,2020-06-30,2020-07-01
1882272,433,23:59:53,00:07:07,324,DeKalb Ave & Hudson Ave,40.689888,-73.981013,261,Johnson St & Gold St,40.694749,-73.983625,38767,Customer,1990,1,2020-06-30,2020-07-01

In [ ]:
june_df.to_csv("db/june.csv")

In [32]:
feb_df["starthour"]=feb_df["starttime"].astype(str).str[:-6]
apr_df["starthour"]=apr_df["starttime"].astype(str).str[:-6]
june_df["starthour"]=june_df["starttime"].astype(str).str[:-6]
feb_df["endhour"]=feb_df["stoptime"].astype(str).str[:-6]
apr_df["endhour"]=apr_df["stoptime"].astype(str).str[:-6]
june_df["endhour"]=june_df["stoptime"].astype(str).str[:-6]

C:\Users\paras\Anaconda3\envs\PythonData2020_1\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\paras\Anaconda3\envs\PythonData2020_1\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\paras\Anaconda3\envs\PythonData2020_1\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\paras\Anaconda3\envs\PythonData2020_1\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\paras\Anaconda3\envs\PythonData2020_1\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\paras\Anaconda3\envs\PythonData2020_1\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [41]:
new_df=pd.DataFrame(apr_df.groupby(["starthour"]).count())
new_df["starthour"]=new_df["tripduration"]+feb_df.groupby(["starthour"]).count()['starthour']
new_df["starthour"]=new_df["tripduration"]+apr_df.groupby(["starthour"]).count()['starthour']
new_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,startdate,stopdate,endhour
starthour,,,,,,,,,,,,,,,,,,
00,1317,1317,1317,1317,1317,1317,1317,1317,1317,1317,1317,1317,1317,1317,1317,1317,1317,1317
01,757,757,757,757,757,757,757,757,757,757,757,757,757,757,757,757,757,757
02,403,403,403,403,403,403,403,403,403,403,403,403,403,403,403,403,403,403
03,320,320,320,320,320,320,320,320,320,320,320,320,320,320,320,320,320,320
04,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375
05,1015,1015,1015,1015,1015,1015,1015,1015,1015,1015,1015,1015,1015,1015,1015,1015,1015,1015
06,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273
07,7235,7235,7235,7235,7235,7235,7235,7235,7235,7235,7235,7235,7235,7235,7235,7235,7235,7235
08,7949,7949,7949,7949,7949,7949,7949,7949,7949,7949,7949,7949,7949,7949,7949,7949,7949,7949
09,7635,7635,7635,7635,7635,7635,7635,7635,7635,7635,7635,7635,7635,7635,7635,7635,7635,7635
10,9175,9175,9175,9175,9175,9175,9175,9175,9175,9175,9175,9175,9175,9175,9175,9175,9175,9175
11,11974,11974,11974,11974,11974,11974,11974,11974,11974,11974,11974,11974,11974,11974,11974,11974,11974,11974
12,15123,15123,15123,15123,15123,15123,15123,15123,15123,15123,15123,15123,15123,15123,15123,15123,15123,15123
13,18183,18183,18183,18183,18183,18183,18183,18183,18183,18183,18183,18183,18183,18183,18183,18183,18183,18183
14,20057,20057,20057,20057,20057,20057,20057,20057,20057,20057,20057,20057,20057,20057,20057,20057,20057,20057
15,21280,21280,21280,21280,21280,21280,21280,21280,21280,21280,21280,21280,21280,21280,21280,21280,21280,21280
16,23177,23177,23177,23177,23177,23177,23177,23177,23177,23177,23177,23177,23177,23177,23177,23177,23177,23177
17,25650,25650,25650,25650,25650,25650,25650,25650,25650,25650,25650,25650,25650,25650,25650,25650,25650,25650
18,23850,23850,23850,23850,23850,23850,23850,23850,23850,23850,23850,23850,23850,23850,23850,23850,23850,23850
19,16640,16640,16640,16640,16640,16640,16640,16640,16640,16640,16640,16640,16640,16640,16640,16640,16640,16640
20,8392,8392,8392,8392,8392,8392,8392,8392,8392,8392,8392,8392,8392,8392,8392,8392,8392,8392
21,4390,4390,4390,4390,4390,4390,4390,4390,4390,4390,4390,4390,4390,4390,4390,4390,4390,4390
22,3234,3234,3234,3234,3234,3234,3234,3234,3234,3234,3234,3234,3234,3234,3234,3234,3234,3234
23,2257,2257,2257,2257,2257,2257,2257,2257,2257,2257,2257,2257,2257,2257,2257,2257,2257,2257

In [43]:
new=pd.DataFrame(apr_df.groupby(["endhour"]).count())
new

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,startdate,stopdate,starthour
endhour,,,,,,,,,,,,,,,,,,
00,1610,1610,1610,1610,1610,1610,1610,1610,1610,1610,1610,1610,1610,1610,1610,1610,1610,1610
01,846,846,846,846,846,846,846,846,846,846,846,846,846,846,846,846,846,846
02,486,486,486,486,486,486,486,486,486,486,486,486,486,486,486,486,486,486
03,347,347,347,347,347,347,347,347,347,347,347,347,347,347,347,347,347,347
04,357,357,357,357,357,357,357,357,357,357,357,357,357,357,357,357,357,357
05,797,797,797,797,797,797,797,797,797,797,797,797,797,797,797,797,797,797
06,3427,3427,3427,3427,3427,3427,3427,3427,3427,3427,3427,3427,3427,3427,3427,3427,3427,3427
07,6390,6390,6390,6390,6390,6390,6390,6390,6390,6390,6390,6390,6390,6390,6390,6390,6390,6390
08,7989,7989,7989,7989,7989,7989,7989,7989,7989,7989,7989,7989,7989,7989,7989,7989,7989,7989
09,7492,7492,7492,7492,7492,7492,7492,7492,7492,7492,7492,7492,7492,7492,7492,7492,7492,7492
10,8324,8324,8324,8324,8324,8324,8324,8324,8324,8324,8324,8324,8324,8324,8324,8324,8324,8324
11,10724,10724,10724,10724,10724,10724,10724,10724,10724,10724,10724,10724,10724,10724,10724,10724,10724,10724
12,13926,13926,13926,13926,13926,13926,13926,13926,13926,13926,13926,13926,13926,13926,13926,13926,13926,13926
13,16467,16467,16467,16467,16467,16467,16467,16467,16467,16467,16467,16467,16467,16467,16467,16467,16467,16467
14,19363,19363,19363,19363,19363,19363,19363,19363,19363,19363,19363,19363,19363,19363,19363,19363,19363,19363
15,20689,20689,20689,20689,20689,20689,20689,20689,20689,20689,20689,20689,20689,20689,20689,20689,20689,20689
16,22750,22750,22750,22750,22750,22750,22750,22750,22750,22750,22750,22750,22750,22750,22750,22750,22750,22750
17,24977,24977,24977,24977,24977,24977,24977,24977,24977,24977,24977,24977,24977,24977,24977,24977,24977,24977
18,25688,25688,25688,25688,25688,25688,25688,25688,25688,25688,25688,25688,25688,25688,25688,25688,25688,25688
19,19710,19710,19710,19710,19710,19710,19710,19710,19710,19710,19710,19710,19710,19710,19710,19710,19710,19710
20,10925,10925,10925,10925,10925,10925,10925,10925,10925,10925,10925,10925,10925,10925,10925,10925,10925,10925
21,5330,5330,5330,5330,5330,5330,5330,5330,5330,5330,5330,5330,5330,5330,5330,5330,5330,5330
22,3505,3505,3505,3505,3505,3505,3505,3505,3505,3505,3505,3505,3505,3505,3505,3505,3505,3505
23,2542,2542,2542,2542,2542,2542,2542,2542,2542,2542,2542,2542,2542,2542,2542,2542,2542,2542

In [34]:
new_df["stophour"]=feb_df.groupby(["endhour"]).count()['tripduration']
new_df["stophour"]=new_df["stophour"]+ apr_df.groupby(["endhour"]).count()['tripduration']
new_df["stophour"]=new_df["stophour"]+june_df.groupby(["endhour"]).count()['tripduration']
new_df

           tripduration  stophour
starthour
00                12837     15183
01                 7522      8789
02                 4288      5238
03                 2629      3081
04                 2606      2617
05                 7524      6025
06                24731     20665
07                46757     40620
08                68866     65170
09                60813     62648
10                56178     54696
11                63751     60026
12                74013     71307
13                80757     76759
14                85232     83828
15                91001     88368
16               100973     97153
17               123198    117890
18               118069    122189
19                90934     98564
20                65031     73363
21                42658     49623
22                29906     33739
23                20501     23234

In [35]:
new_df.to_csv("db/hours.csv")